apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - fake-vllm-exporter.yaml

patches:
  - path: patches/deployment-env.yaml
  - path: patches/service-nodeport.yaml
  - path: namespace-patch.yaml
